Bilet3/Areas/Admin/Controllers/DoctorController.cs
using Bussiness.Abstracts;
using Bussiness.Exceptions;
using Core.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bilet3.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DoctorController : Controller
    {
        IDoctorService _service;

        public DoctorController(IDoctorService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            var doctors = _service.GetAllDoctors();
            return View(doctors);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Doctor doctor) { 
            if(!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                _service.Create(doctor);
            }
            catch (NotFoundException ex)
            {

                ModelState.AddModelError("", ex.Message);
            }
            catch(FileTypeContentException ex)
            {
                ModelState.AddModelError("PhotoFile", ex.Message);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            var doctor=_service.GetDoctor(x=>x.Id == id);
            return View(doctor);
        }
        [HttpPost]
        public IActionResult Update(Doctor doctor)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                _service.Update(doctor.Id,doctor);
            }
            catch (NotFoundException ex)
            {

                ModelState.AddModelError("", ex.Message);
            }
            catch (FileTypeContentException ex)
            {
                ModelState.AddModelError("PhotoFile", ex.Message);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {

            _service.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Bilet3/Controllers/AccountController.cs
using Bilet3.DTOs;
using Core.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Bilet3.Controllers
{
    public class AccountController : Controller
    {
        UserManager<User> _userManager;
        SignInManager<User> _signInManager;
        RoleManager<IdentityRole> _roleManager;

        public AccountController(SignInManager<User> signInManager, UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterDto registerDto)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            User user = new User()
            {
                Name = registerDto.Name,
                Surname = registerDto.Surname,
                Email = registerDto.Email,
                UserName = registerDto.UserName,
            };
            var result = await _userManager.CreateAsync(user, registerDto.Password);
            if (!result.Succeeded)
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
                return View();
            }
            await _userManager.AddToRoleAsync(user, "Admin");
            await _signInManager.SignInAsync(user, false);
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginDto loginDto)
        {
            var user = await _userManager.FindByNameAsync(loginDto.EmailOrUserName);
            if (user == null)
            {
                user = await _userManager.FindByEmailAsync(loginDto.EmailOrUserName);
                if (user == null)
                {
                    ModelState.AddModelError("", "Username ve ya password duzgun daxil edilmeyib!");
                    return View();
                }
            }
            var result = await _signInManager.CheckPasswordSignInAsync(user, loginDto.Password, true);
            if (result.IsLockedOut)
            {
                ModelState.AddModelError("", "Birazdan yeniden cehd edin!");
                return View();
            }
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "UsernameOrEmail ve ya password duzgun daxil edilmeyib");
                return View();
            }
            await _signInManager.SignInAsync(user, loginDto.IsRemember);
            return RedirectToAction("Index", "Home");
        }
        public IActionResult LogOut()
        {
            _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> CreateRole()
        {
            IdentityRole role = new IdentityRole("Admin");
            IdentityRole role1 = new IdentityRole("Member");
            IdentityRole role2 = new IdentityRole("SuperAdmin");
            await _roleManager.CreateAsync(role);
            await _roleManager.CreateAsync(role1);
            await _roleManager.CreateAsync(role2);
            return Ok();
        }
    }
}

Bilet3/Controllers/HomeController.cs
using Bussiness.Abstracts;
using Core.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bilet3.Controllers
{
    public class HomeController : Controller
    {
       
        IDoctorService _doctorService;

        public HomeController(IDoctorService doctorService)
        {
            _doctorService = doctorService;
        }

        public IActionResult Index()
        {
           List<Doctor> doctors = _doctorService.GetAllDoctors();
            return View(doctors);
        }

        

    }
}

Bilet3/Areas/Admin/Views/Doctor/Create.cshtml
@using Core.Models

@model Doctor
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label asp-for="Name" asclass="form-label">Name</label>
            <input asp-for="Name" class="form-control">
            <span asp-validation-for="Name" style="color:red"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Position" asclass="form-label">Position</label>
            <input asp-for="Position" class="form-control">
            <span asp-validation-for="Position" style="color:red"></span>
        </div>
       
        <div class="mb-3">
            <label asp-for="PhotoFile" asclass="form-label">PhotoFile</label>
            <input asp-for="PhotoFile" class="form-control">
            <span asp-validation-for="PhotoFile" style="color:red"></span>
        </div>
        <div asp-validation-summary="All">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Bilet3/Areas/Admin/Views/Doctor/Index.cshtml
@using Core.Models

@model List<Doctor>
@{
    int count = 0;
}
<div class="container">
    <h1>
        Explores
        <a class="btn btn btn-primary" asp-action="Create">Create</a>
    </h1>
</div>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Position</th>
              
                <th scope="col">Image</th>

            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                count++;
                <tr>

                    <td>@count</td>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Position</td>
                    


                    <td>
                        <img width="100%" src="~/Upload/Doctor/@item.ImgUrl" width="150" height="150" />
                    </td>
                    <td>
                        <a class="btn btn-warning" asp-action="Update" asp-controller="Doctor" asp-route-id="@item.Id">Update</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Doctor" asp-route-id="@item.Id">Delete</a>
                    </td>

                </tr>
            }

        </tbody>
    </table>
</div>

Bilet3/Areas/Admin/Views/Doctor/Update.cshtml
@using Core.Models

@model Doctor
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label asp-for="Name" asclass="form-label">Name</label>
            <input asp-for="Name" class="form-control">
            <span asp-validation-for="Name" style="color:red"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Position" asclass="form-label">Position</label>
            <input asp-for="Position" class="form-control">
            <span asp-validation-for="Position" style="color:red"></span>
        </div>

        <div class="mb-3">
            <label asp-for="PhotoFile" asclass="form-label">PhotoFile</label>
            <input asp-for="PhotoFile" class="form-control">
            <span asp-validation-for="PhotoFile" style="color:red"></span>
        </div>
        <div asp-validation-summary="All">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Bilet3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Medicio Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Medicio - v4.10.0
    * Template URL: https://bootstrapmade.com/medicio-free-bootstrap-theme/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    <!-- ======= Top Bar ======= -->
    <div id="topbar" class="d-flex align-items-center fixed-top">
        <div class="container d-flex align-items-center justify-content-center justify-content-md-between">
            <div class="align-items-center d-none d-md-flex">
                <i class="bi bi-clock"></i> Monday - Saturday, 8AM to 10PM
            </div>
            <div class="d-flex align-items-center">
                <i class="bi bi-phone"></i> Call us now +1 5589 55488 55
            </div>
        </div>
    </div>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">

            <a href="index.html" class="logo me-auto"><img src="~/assets/img/logo.png" alt=""></a>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <h1 class="logo me-auto"><a href="index.html">Medicio</a></h1> -->

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    <li><a class="nav-link scrollto " href="#hero">Home</a></li>
                    <li><a class="nav-link scrollto" href="#about">About</a></li>
                    <li><a class="nav-link scrollto" href="#services">Services</a></li>
                    <li><a class="nav-link scrollto" href="#departments">Departments</a></li>
                    <li><a class="nav-link scrollto" href="#doctors">Doctors</a></li>
                    <li class="dropdown">
                        <a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li><a href="#">Drop Down 1</a></li>
                            <li class="dropdown">
                                <a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                                <ul>
                                    <li><a href="#">Deep Drop Down 1</a></li>
                                    <li><a href="#">Deep Drop Down 2</a></li>
                                    <li><a href="#">Deep Drop Down 3</a></li>
                                    <li><a href="#">Deep Drop Down 4</a></li>
                                    <li><a href="#">Deep Drop Down 5</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Drop Down 2</a></li>
                            <li><a href="#">Drop Down 3</a></li>
                            <li><a href="#">Drop Down 4</a></li>
                        </ul>
                    </li>
                    <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a class="nav-link scrollto" >@User.Identity.Name</a></li>
                        <li><a class="nav-link scrollto" asp-action="logOut" asp-controller="account">Log Out</a></li>

                    }
                    else
                    {
                        <li><a class="nav-link scrollto"  asp-action="Register" asp-controller="Account">Register</a></li>
                        <li><a class="nav-link scrollto" asp-action="Login" asp-controller="Account">Login</a></li>


                    }
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

            <a href="#appointment" class="appointment-btn scrollto"><span class="d-none d-md-inline">Make an</span> Appointment</a>

        </div>
    </header><!-- End Header -->
    @RenderBody()

    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-info">
                            <h3>Medicio</h3>
                            <p>
                                A108 Adam Street <br>
                                NY 535022, USA<br><br>
                                <strong>Phone:</strong> +1 5589 55488 55<br>
                                <strong>Email:</strong> info@example.com<br>
                            </p>
                            <div class="social-links mt-3">
                                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-4 col-md-6 footer-newsletter">
                        <h4>Our Newsletter</h4>
                        <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                        <form action="" method="post">
                            <input type="email" name="email"><input type="submit" value="Subscribe">
                        </form>

                    </div>

                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>Medicio</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/medicio-free-bootstrap-theme/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>

</body>

</html>